### ISSUE TITLE
CROS エラーが発生しデータが取得できない

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-opendata-warning-view#2]
## 問題

Chrome 以外のブラウザでアクセスする CROS エラーが発生しデータが取得できません。

https://warnings.stop-covid19-hyogo.org/

### スクリーンショット

<img width="569" alt="スクリーンショット 2020-09-20 17 20 47" src="https://user-images.githubusercontent.com/2575204/93706913-bda1fd00-fb65-11ea-820c-c6476bccb2cb.png">

## 対策案

どちらがよいと思いますか？

### 1. Netlify に `open_data_warnings.json` もアップロードするよう修正

- まとめサイトとサイトを分割できる

### 2. まとめサイトの中にデータ検証結果表示ページを追加する

- 既存の仕組みを流用できる

**Comment by rioil** [comment]
まとめサイトへの影響を気にせずに検証ツールの変更を行えるので，1の方がいいと思います．

**Comment by ohyama** [comment]
@Nekoya3 さんが修正してくれたので、現サイトのまま進めることにします。
