### ISSUE TITLE
修正済みの警告の必要性の検討

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-opendata-warning-view#3]
修正済みの警告は必要でしょうか？

機能が複雑になり、説明しづらいので無くても良い気がしているのですがどう思いますか？

**Comment by rioil** [comment]
修正済みの警告は，修正されているのを確認した日時を持つようにすれば，修正が正しくできたかの確認に使えて役に立つのかなと思います．
ただ，未修整の警告から消えれば修正できていることは確認できるので，実装・維持にコストがかかりすぎるのであれば無くても良い気がします．

**Comment by ohyama** [comment]
@rioil 実装の手間もありますが、先方の運用がどうなるのか想像が付かないので、とりあえずは当日の検証結果を表示するのみで良い気がしてるのですがいかがでしょうか？

**Comment by rioil** [comment]
たしかに今のところは最低限必要な当日の検証結果だけで良いと思います。
